name: Deploy Docker Image

on:
  workflow_run:
    workflows: ["Build and Push Docker Image"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.6.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy Docker image to server
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@43.204.96.32 << 'EOF'
            # Stop and remove the existing container if it exists
            docker stop python-appghactions || true
            docker rm python-appghactions || true
            
            # Pull the latest Docker image
            docker pull ckdh0799/python-app:${{ github.event.workflow_run.head_run_number }}
            
            # Run the new Docker container
            docker run -itd --name python-appghactions -p 6000:5000 ckdh0799/python-app:${{ github.event.workflow_run.head_run_number }}
          EOF
